### ISSUE TITLE
PS2 scan code conversion interface

### ISSUE THREAD

**Issue by bicknrown** [makeopensource/mOS#7]
An interface to take scan codes from the PS2 keyboard interface and output ASCII text. (probably a character at a time)

there is a state machine for this, we have to implement it.

modifier keys should be supported, and it would be helpful to have a generic interface for the conversion, and be able to build system "keyboard shortcuts" on top of that.

**Comment by anxiety-fan** [comment]
taking this lol

**Comment by anxiety-fan** [comment]
Unassigning myself from PS/2. Going to focus on USB (HID) in order to get keyboard functional. To anyone who wants to pick this up: My partial work is in the ps2_archive branch on my fork if you want to use that as a starting point. Be warned: PS/2 is a bad standard that has many eccentricities -- proceed with caution. (Or you will get it in 3 days and I will look like a fool -- wouldn't be the first time)

**Comment by Sploder12** [comment]
I will try to finish from where you left off. Although, I've been trying to figure it out for 2 hours now and haven't made any progress at all.
